# The first entry is the official or most commonly used value, any other entries are also in use.
dasExtensions_by_sbMediaType = {
  b"application/x-bzpdf":                ["pdf"],
  b"application/x-gzpdf":                ["pdf"],
  b"application/gzip":                   ["gz"],
  b"application/ico":                    ["ico"],
  b"application/ecmascript":             ["es", "as"],
  b"application/x-ecmascript":           ["es", "as"],
  b"application/x-java-applet":          ["class"],
  b"application/x-java-vm":              ["class"],
  b"application/javascript":             ["js"],
  b"application/x-javascript":           ["js"],
  b"application/msword":                 ["doc", "dot", "rtf"],
  b"application/x-navi-animation":       ["ani"],
  b"application/octet-stream":           ["bin"],
  b"application/ogg":                    ["ogg"],
  b"application/pdf":                    ["pdf"],
  b"application/x-pdf":                  ["pdf"],
  b"application/rss+xml":                ["rss"],
  b"application/rtf":                    ["rtf"],
  b"application/x-sami":                 ["sami", "smi"],
  b"application/smil":                   ["smi"],
  b"application/smil+xml":               ["smi"],
  b"application/x-shockwave-flash":      ["swf"],
  b"application/x-vbs":                  ["vbs"],
  b"application/vnd.ms-wpl":             ["wpl"],
  b"application/x-win-bitmap":           ["cur"],
  b"application/xhtml+xml":              ["xhtml", "xhtm", "xht"],
  b"text/xsl":                           ["xsl"],
  b"text/xslt":                          ["xslt"],
  b"application/xml":                    ["xml"],
  b"text/xml":                           ["xml"],
  
  b"audio/3gpp":                         ["3gp"],
  b"audio/3gpp2":                        ["3g2"],
  b"audio/x-aiff":                       ["aif"],
  b"audio/basic":                        ["snd"],
  b"audio/x-matroska":                   ["mka"],
  b"audio/mid":                          ["mid"],
  b"audio/mp4":                          ["mp4"],
  b"audio/mp4a-latm":                    ["m4a"],
  b"audio/mpeg":                         ["mp3", "mp2", "mp1"],
  b"audio/x-mpeg":                       ["mp3", "mp2", "mp1"],
  b"audio/x-ms-wax":                     ["wax"],
  b"audio/x-ms-wma":                     ["wma"],
  b"audio/ogg":                          ["ogg"],
  b"audio/wav":                          ["wav"],
  b"audio/x-wav":                        ["wav"],
  
  b"image/bmp":                          ["bmp"],
  b"image/x-emf":                        ["emf"],
  b"image/gif":                          ["gif"],
  b"image/ico":                          ["ico"],
  b"image/icon":                         ["ico"],
  b"image/x-icon":                       ["ico"],
  b"image/jpeg":                         ["jpeg", "jpg"],
  b"image/pjpeg":                        ["jpeg", "jpg"],
  b"image/png":                          ["png"],
  b"image/rle":                          ["rle"],
  b"image/svg+xml":                      ["svg"],
  b"image/x-targa":                      ["tga"],
  b"image/x-tga":                        ["tga"],
  b"image/tiff":                         ["tif"],
  b"image/x-tiff":                       ["tif"],
  b"image/tiff-fx":                      ["tif"],
  b"image/vnd.microsoft.icon":           ["ico"],
  b"image/x-windows-bmp":                ["bmp"],
  b"image/x-wmf":                        ["wmf"],
  b"image/x-xbitmap":                    ["xbm"],
  b"image/x-xbm":                        ["xbm"],
  b"image/xbm":                          ["xbm"],
  b"image/x-win-bitmap":                 ["cur"],
  
  b"text/css":                           ["css"],
  b"text/html":                          ["html", "htm"],
  b"text/ico":                           ["ico"],
  b"text/ecmascript":                    ["es", "as"],
  b"text/x-ecmascript":                  ["es", "as"],
  b"text/javascript":                    ["js"],
  b"text/jscript":                       ["js"],
  b"text/x-javascript":                  ["js"],
  b"application/json":                   ["json"],
  b"text/markdown":                      ["md"],
  b"text/plain":                         ["txt"],
  b"text/rtf":                           ["rtf"],
  b"text/vbs":                           ["vbs"],
  b"text/vbscript":                      ["vbs"],
  
  b"video/3gpp":                         ["3gp"],
  b"video/3gpp2":                        ["3g2"],
  b"video/x-flv":                        ["flv"],
  b"video/x-ivf":                        ["ivf"],
  b"video/x-m4v":                        ["m4v"],
  b"video/x-matroska":                   ["mkv", "mk3d", "mks"],
  b"video/mp4":                          ["mp4"],
  b"video/mpeg":                         ["mpeg", "mpg"],
  b"video/x-msvideo":                    ["avi"],
  b"video/x-ms-asf":                     ["asx"],
  b"video/x-ms-wmv":                     ["wmv"],
  b"video/x-ms-wmx":                     ["wmx"],
  b"video/x-ms-wvx":                     ["wvx"],
  b"video/ogg":                          ["ogv"],
  b"video/quicktime":                    ["qt", "mov"],
  b"video/webm":                         ["webm"],
};