# The first entry is the official or most commonly used value, any other entries are also in use.
dasbMediaTypes_by_sExtension = {
  "3gp":      [b"video/3gpp",                     b"audio/3gpp"],
  "3g2":      [b"video/3gpp2",                    b"audio/3gpp2"],
  "aif":      [b"audio/x-aiff"],
  "ani":      [b"application/x-navi-animation"],
  "as":       [b"application/ecmascript"],
  "asx":      [b"video/x-ms-asf"],
  "avi":      [b"video/x-msvideo"],
  "bat":      [b"text/plain"],
  "bmp":      [b"image/bmp",                      b"image/x-windows-bmp"],
  "class":    [b"application/x-java-applet",      b"application/x-java-vm"],
  "cmd":      [b"text/plain"],
  "css":      [b"text/css"],
  "cur":      [b"image/vnd.microsoft.icon",       b"image/x-win-bitmap", b"application/x-win-bitmap"],
  "emf":      [b"image/x-emf"],
  "es":       [b"application/ecmascript",         b"application/x-ecmascript", b"text/ecmascript", b"text/x-ecmascript"],
  "flv":      [b"video/x-flv"],
  "gif":      [b"image/gif"],
  "gz":       [b"application/gzip"],
  "htm":      [b"text/html"],
  "html":     [b"text/html"],
  "ico":      [b"image/vnd.microsoft.icon",       b"text/ico", b"image/ico", b"image/icon", b"application/ico", b"image/x-icon"],
  "ivf":      [b"video/x-ivf"],
  "jpg":      [b"image/jpeg",                     b"image/pjpeg"],
  "jpeg":     [b"image/jpeg",                     b"image/pjpeg"],
  "js":       [b"application/javascript",         b"application/x-javascript", b"text/javascript", b"text/jscript", b"text/x-javascript"],
  "json":     [b"application/json"],
  "m2v":      [b"video/mpeg"],
  "m4a":      [b"audio/mp4a-latm"],
  "m4v":      [b"video/x-m4v"],
  "md":       [b"text/markdown"],
  "mid":      [b"audio/mid"],
  "mk3d":     [b"video/x-matroska"],
  "mka":      [b"audio/x-matroska"],
  "mks":      [b"video/x-matroska"],
  "mkv":      [b"video/x-matroska"],
  "mov":      [b"video/quicktime"],
  "mp3":      [b"audio/mpeg"],
  "mp4":      [b"video/mp4",                      b"audio/mp4"],
  "mpa":      [b"audio/mpeg",                     b"video/mpeg"],
  "mpg":      [b"video/mpeg",                     b"application/mpeg", b"application/x-mpeg"],
  "rle":      [b"image/rle"],
  "ogg":      [b"application/ogg"],
  "oga":      [b"audio/ogg"],
  "ogv":      [b"video/ogg"],
  "ogx":      [b"application/ogg"],
  "opus":     [b"audio/ogg"],
  "otf":      [b"application/octet-stream"],
  "png":      [b"image/png"],
  "pdf":      [b"application/pdf",                b"application/x-pdf", b"application/x-bzpdf", b"application/x-gzpdf"],
  "py":       [b"text/plain"],
  "qt":       [b"video/quicktime"],
  "rss":      [b"application/rss+xml"],
  "rtf":      [b"text/rtf",                       b"application/rtf", b"application/msword"],
  "sami":     [b"application/x-sami"],
  "smi":      [b"application/smil",               b"application/smil+xml", b"application/x-sami"],
  "snd":      [b"audio/basic"],
  "spx":      [b"audio/ogg"],
  "svg":      [b"image/svg+xml"],
  "swf":      [b"application/x-shockwave-flash"],
  "tga":      [b"image/x-tga",                    b"image/x-targa"],
  "tif":      [b"image/tiff",                     b"image/x-tiff", b"image/tiff-fx"],
  "ttf":      [b"application/octet-stream"],
  "txt":      [b"text/plain"],
  "vbs":      [b"text/vbscript",                  b"application/x-vbs", b"text/vbs"],
  "wav":      [b"audio/wav",                      b"audio/x-wav"],
  "wax":      [b"audio/x-ms-wax"],
  "webm":     [b"video/webm"],
  "wma":      [b"audio/x-ms-wma"],
  "wmf":      [b"image/x-wmf"],
  "wmv":      [b"audio/x-ms-wmv"],
  "wmx":      [b"video/x-ms-wmx"],
  "wpl":      [b"application/vnd.ms-wpl"],
  "wvx":      [b"video/x-ms-wvx"],
  "xbm":      [b"image/x-xbitmap",                b"image/x-xbm", b"image/xbm"],
  "xhtml":    [b"application/xhtml+xml"],
  "xsl":      [b"application/xml",                b"text/xml", b"text/xsl"],
  "xslt":     [b"application/xml",                b"text/xml", b"text/xslt"],
  "xml":      [b"application/xml",                b"text/xml", b"text/xml"],
};
